x-uffizzi:
  ingress:
    service: app
    port: 8080
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true

services:
  webapp:
    build: .
      context: https://github.com/Abdulrouf48/mirror-leech-telegram-bot
      dockerfile: Dockerfile    
