x-uffizzi:
  ingress:
    service: app
    port: 3000
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true

services:
  app:
    build:
      context: https://github.com/Abdulrouf48/mirror-leech-telegram-bot
      dockerfile: Dockerfile
