# Uffizzi extension
x-uffizzi:
  ingress:
    service: loadbalancer
    port: 8080  
  continuous_preview:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true


  worker:
    build: ./worker      # Assumes Dockerfile exists in this repo  
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build: ./result     
    context: Dockerfile  # Or you can specify an alternate monorepo
    environment:
      PORT: 8088


