x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    context: https://github.com/Abdulrouf48/mirror-leech-telegram-bot
    dockerfile: Dockerfile
    environment:
      NODE_ENV: staging
    deploy:
      resources:
        limits:
          memory: 2000M 
    restart: unless-stopped
    ports:
      - "8000:8000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
volumes:
  data:
  
