    x-uffizzi:
      ingress:
        service: app
        port: 80

    services:
      app:
        build:
          context: https://github.com/ilhammass/mirror-leech-telegram-bot
          dockerfile: Dockerfile
