x-uffizzi:
  ingress:
    service: vencoder
    port: 80
  continuous_preview:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true
services:
  vencoder:
    image: veapapa:latest
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
